### ISSUE TITLE
Support get size info by context

### ISSUE THREAD

**Issue by jhen0409** [machadogj/react-native-layout-tester#1]
Just a idea, a decorators function: (just like `react-redux` connect)

``` js
import React, { Component, PropTypes } from 'react';
import { getLayoutSize } from 'react-native-layout-tester';

@getLayoutSize(layout => ({
  deviceName: layout.label,
  deviceWidth: layout.width,
  deviceHeight: layout.height,
}))
class Comp extends Component {
  static propTypes = {
    deviceName: PropTypes.string,
    deviceWidth: PropTypes.number,
    deviceHeight: PropTypes.number,
  };

  render() { ... }
}
```

Also, we can have a `default` config, it can get `Dimensions` info and no test wrapper. It can be used for production, and keep the same code.

@machadogj what do you think?

**Comment by machadogj** [comment]
I like the idea. It can help decouple styles from physical dimensions too which could be useful.

**Comment by jhen0409** [comment]
@machadogj I'll make a PR for this, can you review #2 first?

**Comment by machadogj** [comment]
Yes, I'll review it today. Thanks.

**Comment by machadogj** [comment]
@jhen0409  Done. Updated repo and npm!

**Comment by machadogj** [comment]
Tested the PR and works like a charm. Added a minor, updated docs and published to npm.
Thanks for your help!
