### ISSUE TITLE
Component viewer/selector

### ISSUE THREAD

**Issue by machadogj** [machadogj/react-native-layout-tester#6]
Receive the list of components with sample props to visualise.

**Comment by machadogj** [comment]
Initial version here: https://github.com/machadogj/react-native-layout-tester/tree/component-viewer.
@jhen0409 can I have your input on this one? You can see it in action here: http://recordit.co/nAYVNIF3WV.

**Comment by machadogj** [comment]
Samples of how this looks. It supports both modes:

![component-viewer-sample](https://cloud.githubusercontent.com/assets/671212/16655335/358d622e-4430-11e6-84df-6193f7da748f.gif)
![layout-tester-sample](https://cloud.githubusercontent.com/assets/671212/16655336/35ae1438-4430-11e6-9bb7-1c2cd359387d.gif)

**Comment by jhen0409** [comment]
Awesome! Also, can we have a custom prop for each menu item? Currently I prefer to control page fully with state (including NavigationExperimental). If we use independent component for each menu item, it would be a bit complicated.

**Comment by machadogj** [comment]
Is this what you mean? https://github.com/machadogj/react-native-layout-tester/tree/component-viewer#testing-different-components
(btw, I updated the readme)

**Comment by jhen0409** [comment]
I mean menu item of sidebar, we can custom onPress for each menu item. What do you think?

A idea:

``` js
const sidebarItems = [
  { name: "...", onPress: () => {...}, subItems: [...] },
  { name: "...", component: <Home /> },
];

<LayoutTester sideBarItems={sideBarItems} />
```

**Comment by machadogj** [comment]
I see what you mean.

Currently I think it works well with Presentational components (https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0#.7aehm1t3z) so that you leave the application state out of the component.

With your proposed change, it could test the wiring of container component as well. So the code inside the onPress would modify your apps internal state to display the correct scene/component?

**Comment by machadogj** [comment]
@jhen0409 I don't want to clutter this package, so I created another one here: https://github.com/machadogj/react-native-components-viewer.

I also believe that the getLayout should be moved outside of this package if possible, so controls don't necessarily depend on it to be "testable". What do you think?

**Comment by jhen0409** [comment]
> Currently I think it works well with Presentational components (...) so that you leave the application state out of the component.

I agreed. :)

> I also believe that the getLayout should be moved outside of this package if possible, so controls don't necessarily depend on it to be "testable". What do you think?

Should we split LayoutTester context & getLayout decorator to another package, and reuse in LayoutTester? I agreed because it can avoid including rn-layout-tester on production. (Although not a lot of code. lol)

I'll doing next days and send a PR, or you want to do yourself?

**Comment by machadogj** [comment]
Yes, that's what I had in mind. Go ahead if you want, it's mostly your code :-)

Let me know if the need any help.
